apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: voz-bogota
data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  APP_ENV: "production"
  CORS_ORIGINS: "http://localhost"
